import { createFileRoute } from "@tanstack/react-router";
import { Mail, MapPin, Phone } from "lucide-react";
import { PageHero } from "@/components/site-layout";
import { ContactForm } from "@/components/request-form";
import { contact } from "@/lib/site-content";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact — LASISTANT.PRO" }, { name: "description", content: "Contactez LASISTANT.PRO par téléphone ou e-mail pour parler de votre séjour en Tunisie." }, { property: "og:title", content: "Contact — LASISTANT.PRO" }, { property: "og:description", content: "Notre équipe est à votre écoute pour comprendre votre demande." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }, { property: "og:url", content: "/contact" },
], links: [{ rel: "canonical", href: "/contact" }] }), component: ContactPage });

function ContactPage() { return <><PageHero eyebrow="Contact" title="Nous sommes à votre écoute." intro="Expliquez-nous votre besoin. Nous vous aiderons à identifier la prochaine étape la plus utile."/><section className="page-shell section-space grid gap-10 md:grid-cols-[0.8fr_1.2fr]"><div className="grid content-start gap-7">{contact.phones.map((phone,index) => <a key={phone} href={`tel:${phone.replace(/\s/g,"")}`} className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-muted text-primary"><Phone /></span><span><span className="block text-sm text-muted-foreground">Téléphone {index + 1}</span><strong className="mt-1 block">{phone}</strong></span></a>)}<a href={`mailto:${contact.emails[0]}`} className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-muted text-primary"><Mail /></span><span className="min-w-0"><span className="block text-sm text-muted-foreground">E-mail</span><strong className="mt-1 block break-all">{contact.emails[0]}</strong></span></a><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-muted text-primary"><MapPin /></span><span><span className="block text-sm text-muted-foreground">Adresse</span><strong className="mt-1 block">{contact.address}</strong></span></div><a href="https://www.facebook.com/imassist.tant" target="_blank" rel="noreferrer" className="text-sm font-bold text-primary underline underline-offset-4">Retrouvez-nous sur Facebook : imassist Tant</a></div><ContactForm /></section></> }